In [1]:
import numpy as np
a = np.arange(12).reshape(3,4)
print(a)
b = a>4
print(b)
print(a[b])
a[b] = 1
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[0 1 2 3]
 [4 1 1 1]
 [1 1 1 1]]


In [2]:
import numpy as np
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.arange(28).reshape(7,4)
print(names)
print(data)
print(names ==  'Bob')
print(data[names == 'Bob'])
print(data[names == 'Bob',2:])
print(data[names == 'Bob',3])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[ True False False  True False False False]
[[ 0  1  2  3]
 [12 13 14 15]]
[[ 2  3]
 [14 15]]
[ 3 15]


In [3]:
import numpy as np
x = np.arange(10)
print("X = ",x)
print("1st 5 elements",x[:5])
print("from 5",x[5:])
print("mid sub array",x[4:7])
print(x[::2])
print(x[1::2])
print(x[::-1])
print(x[5::-2])

X =  [0 1 2 3 4 5 6 7 8 9]
1st 5 elements [0 1 2 3 4]
from 5 [5 6 7 8 9]
mid sub array [4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [4]:
print("broadcasting")
x = np.arange(10)
x[5:] = 1
print("After",x)
x[::2] = 100
print("After",x)

broadcasting
After [0 1 2 3 4 1 1 1 1 1]
After [100   1 100   3 100   1 100   1 100   1]


In [5]:
x = np.arange(12)
print("original array",x)
view = x[3:7]
print("View",view)
view[1:4] = 99
print("Modified",view)
print("Original array after modification",x)
view[:] = -7
print("Modified",view)
print("X=",x)

original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
View [3 4 5 6]
Modified [ 3 99 99 99]
Original array after modification [ 0  1  2  3 99 99 99  7  8  9 10 11]
Modified [-7 -7 -7 -7]
X= [ 0  1  2 -7 -7 -7 -7  7  8  9 10 11]


In [6]:
x = np.array([[2,8,4,5],
              [7,5,2,9],
              [7,1,12,17]])
print(x[0])
print(x[1])
print(x[2])
print(x[1,0])
print(x[1][0])
print(x[2,2])
print(x[2,-1])
print(x[1,-2])

[2 8 4 5]
[7 5 2 9]
[ 7  1 12 17]
7
7
12
17
2


In [8]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


In [9]:
print(a + b)
print(a - b)
print(a * b)
print(b / a)
print(a ** 2)
print(b % a)
print(b // a)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[4.  2.5 2. ]
[1 4 9]
[0 1 0]
[4 2 2]


In [10]:
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(b, a))


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[4.  2.5 2. ]


In [11]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

c = np.array([[1],
              [2]])

print(a + b)
print(a + c)
d = np.array([1, 2])
print(a * 10)


[[11 22 33]
 [14 25 36]]
[[2 3 4]
 [6 7 8]]
[[10 20 30]
 [40 50 60]]


In [12]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
y = np.array([1, 0, -1])

print(x + y)


[[2 2 2]
 [5 5 5]]


In [13]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])
c = np.array([[1], [2]])
d = np.array([[100], [200]])
e = np.array([1, 2, 3])

print(a + b)
print(a + c)
print(c + d)
print(b * e)


[[11 22 33]
 [14 25 36]]
[[2 3 4]
 [6 7 8]]
[[101]
 [202]]
[10 40 90]


In [14]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

a2 = a.reshape(2, 3)
a3 = a.reshape(3, 2)
a_row = a.reshape(1, 6)
a_col = a.reshape(6, 1)
a_flat = a2.reshape(-1)

print(a2)
print(a3)
print(a_row)
print(a_col)
print(a_flat)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]


In [15]:
import numpy as np

a = np.arange(24)

a2d = a.reshape(4, 6)
a3d = a.reshape(2, 3, 4)
a_flat = a.reshape(-1)

print(a2d)
print(a3d)
print(a_flat)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [16]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 3, 5])

print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)


[ True False  True False]
[False  True False  True]
[False  True False False]
[False False False  True]
[ True  True  True False]
[ True False  True  True]


In [17]:
import numpy as np

a = np.array([1.0, 2.5, 3.1, 4.0])
b = np.array([1.0, 2.0, 3.1, 5.0])

print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)


[ True False  True False]
[False  True False  True]
[False  True False False]
[False False False  True]
[ True  True  True False]
[ True False  True  True]


In [18]:
import numpy as np

a = np.array([10, 20, 30, 40, 50, 60])

print(a[0])      # First element
print(a[-1])     # Last element
print(a[1:4])    # Slice from index 1 to 3
print(a[:3])     # First three elements
print(a[3:])     # From index 3 to end
print(a[::2])    # Every second element
print(a[::-1])   # Reversed array


10
60
[20 30 40]
[10 20 30]
[40 50 60]
[10 30 50]
[60 50 40 30 20 10]


In [19]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [20]:
print(a[0, 0])
print(a[1])
print(a[:, 1])

1
[4 5 6]
[2 5 8]


In [21]:
print(a[0:2, 1:3])
print(a[:, ::2])

[[2 3]
 [5 6]]
[[1 3]
 [4 6]
 [7 9]]


In [22]:
b = np.array([10, 20, 30])
print(a + b)

c = np.array([[1], [2], [3]])
print(a * c)

[[11 22 33]
 [14 25 36]
 [17 28 39]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


In [23]:
print(np.sum(a))
print(np.mean(a, axis=0))
print(np.max(a, axis=1))

45
[4. 5. 6.]
[3 6 9]


In [24]:
import numpy as np

a = np.arange(27).reshape(3, 3, 3)

print(a[0, :, :])
print(a[:, 1, :])
print(a[:, :, 2])
print(a[1:, 0:2, 1:3])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]
[[[10 11]
  [13 14]]

 [[19 20]
  [22 23]]]


In [25]:
import numpy as np
a = np.arange(12).reshape(3, 4)

In [27]:
print(np.transpose(a))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [28]:
a2d = np.array([[1, 2, 3],
                [4, 5, 6]])
print("2D transpose:\n", np.transpose(a2d))

2D transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [29]:
a3d = np.arange(24).reshape(2, 3, 4)
print("\n3D original shape:", a3d.shape)
print("3D transpose (default axes):\n", np.transpose(a3d).shape)


3D original shape: (2, 3, 4)
3D transpose (default axes):
 (4, 3, 2)


In [30]:
print("3D transpose (axes=(1, 0, 2)) shape:", np.transpose(a3d, (1, 0, 2)).shape)
print("3D transpose (axes=(2, 1, 0)) shape:", np.transpose(a3d, (2, 1, 0)).shape)

3D transpose (axes=(1, 0, 2)) shape: (3, 2, 4)
3D transpose (axes=(2, 1, 0)) shape: (4, 3, 2)


In [31]:
b = np.arange(24).reshape(2, 3, 4)
print(np.swapaxes(b, 0, 2))

[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [32]:
a2d = np.array([[1, 2, 3],
                [4, 5, 6]])
print(np.swapaxes(a2d, 0, 1))


[[1 4]
 [2 5]
 [3 6]]


In [33]:
a3d = np.arange(24).reshape(2, 3, 4)
print(np.swapaxes(a3d, 0, 2).shape)
print(np.swapaxes(a3d, 1, 2).shape)

(4, 3, 2)
(2, 4, 3)


In [34]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print(np.matmul(a, b))
print(a @ b)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [35]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

print(np.matmul(a, b))

[[19 22]
 [43 50]]


In [36]:
A = np.array([[[1, 2],
               [3, 4]],

              [[5, 6],
               [7, 8]]])

B = np.array([[[9, 8],
               [7, 6]],

              [[5, 4],
               [3, 2]]])

print(np.matmul(A, B))


[[[23 20]
  [55 48]]

 [[43 32]
  [59 44]]]
